### ISSUE TITLE
ImportError: ../libmkl_gnu_thread.so: invalid ELF header

### ISSUE THREAD

**Issue by juyoungml** [princeton-nlp/WebShop#22]
## I'm submitting a ...

- [X] bug report
- [ ] feature request

## What is the current behavior?

Please describe the current behavior of the WebShop app or agent

- After all the installation and when I try to run `./run_dev.sh`, I get the following error:

```
Traceback (most recent call last):
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/juyoung/webshop/web_agent_site/app.py", line 14, in <module>
    from web_agent_site.engine.engine import (
  File "/home/juyoung/webshop/web_agent_site/engine/engine.py", line 16, in <module>
    from pyserini.search.lucene import LuceneSearcher
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/pyserini/search/__init__.py", line 19, in <module>
    from .lucene import JLuceneSearcherResult, LuceneSimilarities, LuceneFusionSearcher, LuceneSearcher
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/pyserini/search/lucene/__init__.py", line 18, in <module>
    from ._impact_searcher import JImpactSearcherResult, LuceneImpactSearcher
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/pyserini/search/lucene/_impact_searcher.py", line 28, in <module>
    from pyserini.encode import QueryEncoder, TokFreqQueryEncoder, UniCoilQueryEncoder, \
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/pyserini/encode/__init__.py", line 17, in <module>
    from ._base import DocumentEncoder, QueryEncoder, JsonlCollectionIterator,\
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/pyserini/encode/_base.py", line 19, in <module>
    import faiss
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/faiss/__init__.py", line 18, in <module>
    from .loader import *
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: /home/juyoung/.conda/envs/webshop/lib/python3.8/site-packages/faiss/../../.././libmkl_gnu_thread.so: invalid ELF header
```

- FYI, I downloaded Java like this: `sudo apt install openjdk-11-jdk`.

### Steps to Reproduce

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

- I first confronted this error in my environment, so I tried to use a docker image `python:3.8.13-slim` to see if this error can be reproduced. And I get a similar error, too:

```
Traceback (most recent call last):
  File "/usr/local/envs/webshop/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/webshop/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/webshop/web_agent_site/app.py", line 14, in <module>
    from web_agent_site.engine.engine import (
  File "/usr/src/app/webshop/web_agent_site/engine/engine.py", line 16, in <module>
    from pyserini.search.lucene import LuceneSearcher
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/pyserini/search/__init__.py", line 19, in <module>
    from .lucene import JLuceneSearcherResult, LuceneSimilarities, LuceneFusionSearcher, LuceneSearcher
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/pyserini/search/lucene/__init__.py", line 18, in <module>
    from ._impact_searcher import JImpactSearcherResult, LuceneImpactSearcher
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/pyserini/search/lucene/_impact_searcher.py", line 28, in <module>
    from pyserini.encode import QueryEncoder, TokFreqQueryEncoder, UniCoilQueryEncoder, \
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/pyserini/encode/__init__.py", line 17, in <module>
    from ._base import DocumentEncoder, QueryEncoder, JsonlCollectionIterator,\
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/pyserini/encode/_base.py", line 19, in <module>
    import faiss
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/faiss/loader.py", line 65, in <module>
    from .swigfaiss import *
  File "/usr/local/envs/webshop/lib/python3.8/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
```

- It seems like there are some issues with pyserini and faiss for me, but there are no issues about this. Can you help me with set up process?

## What is the expected behavior?

Please describe the desired behavior of the WebShop app or agent

## Motivation for Change

What is the motivation / use case for changing the behavior?

## Please tell us about your environment:

* Version: 2.0.0-beta.X
* Browser:
* Language:

**Comment by imenelydiaker** [comment]
Hello, I'm facing the same issue when running `run_dev.sh`. Did you find a way to solve it ? Are there any updates on this one ?

**Comment by ZhitongGuo** [comment]
I'm facing the same issue while running the setup.sh, and it cannot find the intel mkl library. I wonder if it's because I'm using an apple m2 chip instead of an intel one?

**Comment by kkmjkim** [comment]
I resolved this issue by referring to https://github.com/facebookresearch/faiss/issues/2890
