### ISSUE TITLE
JVM exception occured

### ISSUE THREAD

**Issue by harshraj172** [princeton-nlp/WebShop#24]
Faced the below error :

```
Products loaded.
Keys cleaned.
Attributes loaded.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1181436/1181436 [00:25<00:00, 45656.08it/s]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/conda/envs/webshop/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/webshop/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harsh777111raj/AgentBench/src/tasks/webshop/__init__.py", line 38, in predict
    env = WebAgentTextEnv(observation_mode="text", human_goals=True)
  File "/home/harsh777111raj/AgentBench/src/tasks/webshop/web_agent_site/envs/web_agent_text_env.py", line 61, in __init__
    self.server = SimServer(
  File "/home/harsh777111raj/AgentBench/src/tasks/webshop/web_agent_site/envs/web_agent_text_env.py", line 299, in __init__
    self.search_engine = init_search_engine(num_products=num_products)
  File "/home/harsh777111raj/AgentBench/src/tasks/webshop/web_agent_site/engine/engine.py", line 206, in init_search_engine
    search_engine = LuceneSearcher(os.path.join(BASE_DIR, f'../search_engine/{indexes}'))
  File "/opt/conda/envs/webshop/lib/python3.8/site-packages/pyserini/search/lucene/_searcher.py", line 51, in __init__
    self.object = JLuceneSearcher(index_dir)
  File "jnius/jnius_export_class.pxi", line 270, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 384, in jnius.JavaClass.call_constructor
  File "jnius/jnius_utils.pxi", line 79, in jnius.check_exception
jnius.JavaException: JVM exception occurred: no segments* file found in MMapDirectory@/home/harsh777111raj/AgentBench/src/tasks/webshop/search_engine/indexes lockFactory=org.apache.lucene.store.NativeFSLockFactory@6e4566f1: files: [] org.apache.lucene.index.IndexNotFoundException
```

**Comment by john-b-yang** [comment]
Hi @harshraj172 I'm able to help more actively - When did this error occur? Is it when you ran the WebShop web app?

Can you provide more details around what your set up was like so I can try to recreate it?

**Comment by ysymyth** [comment]
close it due to inactivity but feel free to open a new one!
