### ISSUE TITLE
error when running run_dev.sh

### ISSUE THREAD

**Issue by flbyrne** [princeton-nlp/WebShop#32]
## I'm submitting a ...

- [ x] bug report
- [ ] feature request

## What is the current behavior?

I'm having the following error when running run_dev.sh (after doing all the previous steps):
anybody was able to fix this:?

(webshop) esf0@DESKTOP-5CVVTN8:~/webshop$ ./run_dev.sh                                                               Traceback (most recent call last):                                                                                     File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/runpy.py", line 194, in _run_module_as_main                      return _run_code(code, main_globals, None,                                                                         File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/runpy.py", line 87, in _run_code                                 exec(code, run_globals)                                                                                            File "/home/esf0/webshop/web_agent_site/app.py", line 23, in <module>                                                  from web_agent_site.engine.goal import get_reward, get_goals                                                       File "/home/esf0/webshop/web_agent_site/engine/goal.py", line 6, in <module>                                           import spacy                                                                                                       File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/__init__.py", line 14, in <module>           from . import pipeline  # noqa: F401                                                                               File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>                                                                                                                        from .attributeruler import AttributeRuler                                                                         File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>                                                                                                                  from .pipe import Pipe                                                                                             File "spacy/pipeline/pipe.pyx", line 8, in init spacy.pipeline.pipe                                                 
 File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/training/__init__.py", line 11, in <module>                                                                                                                       from .callbacks import create_copy_from_base_model  # noqa: F401                                                   File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/training/callbacks.py", line 3, in <module>                                                                                                                       from ..language import Language                                                                                    File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/language.py", line 25, in <module>           from .training.initialize import init_vocab, init_tok2vec                                                          File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/training/initialize.py", line 14, in <module>                                                                                                                     from .pretrain import get_tok2vec_ref                                                                              File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/training/pretrain.py", line 16, in <module>                                                                                                                       from ..schemas import ConfigSchemaPretrain                                                                         File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/site-packages/spacy/schemas.py", line 216, in <module>           class TokenPattern(BaseModel):                                                                                     File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__                                           File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer                                             File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__                                          File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare                                           File "pydantic/fields.py", line 545, in pydantic.fields.ModelField._type_analysis                                    File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis                                    File "/home/esf0/anaconda3/envs/webshop/lib/python3.8/typing.py", line 774, in __subclasscheck__                       return issubclass(cls, self.__origin__)                                                                          TypeError: issubclass() arg 1 must be a class                                                                        (webshop) esf0@DESKTOP-5CVVTN8:~/webshop$                   

### Steps to Reproduce

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

## What is the expected behavior?

Please describe the desired behavior of the WebShop app or agent

## Motivation for Change

What is the motivation / use case for changing the behavior?

## Please tell us about your environment:

* Version: 2.0.0-beta.X
* Browser:
* Language:

**Comment by ai-nikolai** [comment]
What exactly are your issues? It seems your code is not importing spacy properly, which I had as well. Possibly try:
1. remove `spacy==3.3.0` from `requirements.txt`
2. `conda install spacy` before you run `./setup.sh`

I had a lot of problems when running the installation script, so maybe some parts failed there for you?

This PR https://github.com/princeton-nlp/WebShop/pull/34 fixes things for me.

**Comment by ysymyth** [comment]
closing for now but feel free to reopen
