### ISSUE TITLE
[Installation error] FileURLRetrievalError: Cannot retrieve the public link of the file.

### ISSUE THREAD

**Issue by lewtun** [princeton-nlp/WebShop#40]
## I'm submitting a ...

- [x] bug report
- [ ] feature request

## What is the current behavior?

I am following the [setup instructions](https://github.com/princeton-nlp/WebShop?tab=readme-ov-file#-setup) and after creating the Conda env and running `./setup.sh -d small` I am hitting this error:

```
Traceback (most recent call last):
  File "/fsx/lewis/miniconda3/envs/webshop/lib/python3.8/site-packages/gdown/download.py", line 267, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "/fsx/lewis/miniconda3/envs/webshop/lib/python3.8/site-packages/gdown/download.py", line 55, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/fsx/lewis/miniconda3/envs/webshop/lib/python3.8/site-packages/gdown/download_folder.py", line 325, in download_folder
    local_path = download(
  File "/fsx/lewis/miniconda3/envs/webshop/lib/python3.8/site-packages/gdown/download.py", line 278, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1sFrSDCnvFYz5XePd2bvFIIr3hkC5DUxA

but Gdown can't. Please check connections and permissions.
Downloading example trajectories complete
```

### Steps to Reproduce

Follow steps 1-5 of the Setup section in the README with

```
./setup.sh -d small
```

## What is the expected behavior?

No error during install.

## Motivation for Change

What is the motivation / use case for changing the behavior?

## Please tell us about your environment:

* Version: 2.0.0-beta.X
* Browser:
* Language:

**Comment by lewtun** [comment]
Sorry this was a faulty connection issue on my side - closing the issue.
